### ISSUE TITLE
Create a new project command

### ISSUE THREAD

**Issue by connorhsm** [voteflux/flux-projects#3]
Need a command to create a new project.
This will heavily rely on a robust question and answer system that will be reused throughout the bot. Question system #4 

A project requires the following data:
- ID - INT10 - Auto generated by MySQL
- Title - VARCHAR128 - User input
- Start date - DATE (YYYY-MM-DD) - User input
- End date - DATE (YYYY-MM-DD) - User input
- Description - VARCHAR512 - User input
- Outcomes - VARCHAR256 - User input
- Deliverables - VARCHAR256 - User input
- Objective - INT4 - Predefined user input
- Lead - INT64 - Discord ID of the project creator
- Resources - VARCHAR16 - Predefined user input
- Official - INT1 - Conditional user input
- Status - INT4 - Predefined user input

**Comment by BenBallingall** [comment]
This is actually so beautiful. 

Like, Discord probably don't know their platform can do this shit beautiful.

**Comment by KipCrossing** [comment]
The Predefined user inputs can be done with emojis
